<!DOCTYPE html>
<head>
	<title>Rdein Lab</title>
	<link rel="stylesheet" type="text/css" href="/../style.css" />
</head>

<body>

<?php include_once("navbar.php") ?>

<div class="column">

	<div class="header"><h2>About Us</h2></div>
	<div class="content"><p><b>Rdein Laboratories</b> is a medical research and development group dedicated to the study of Originium and Originium-based infections. We specialise in the environmental effects of Originium spread as well as working in tandem with pharmaceutical companies to produce a panacea for Infected across Terra.</p></div>

	<div class="header"><h2>Locations</h2></div>
	<div class="content"><p>We are headquartered in the <b>Rhinelands</b>, but we have research enclaves all around Terra. Of note are the enclaves in the <b>South Pole</b>, <b>Victoria</b>, <b>Rokkenjima</b>, and an attache with <b>Rhodes Island</b>.</p></div>

	<div class="header"><h2>Staff</h2></div>
	<div class="content"><p>Our staff consists of many of the brightest minds Terra has to offer. The expertise we have on board Rdein Lab ranges from mechatronic engineering to data analysis and even frontline medical care. Due to the often dangerous nature of our work, most of our field technicians operate with codenames to preserve anonymity.</p></div>

</div>

<div class="column side">

	<div class="sidebar top"><h2>Booking Information</h2></div>
	<div class="sidebar"><p>Please do not book our services if your enquiry involves cooking ramen in your mouth by drinking boiling water. Not again.</p></div>

</div>

</body>
</html>