<!DOCTYPE html>
<body>

<?php include_once("navbar.php") ?>

</br>

<div class="form">
<form action="/auth" method="post">

<table align="center">
	<tr>
		<td><label for="username">Username:</label></td>
		<td><input type="text" name="username"></td>
	</tr>
	<tr>
		<td><label for="pass">Password:</label></td>
		<td><input type="password" name="pass"></td>
	</tr>
	<tr>
		<td colspan="2" align="center"><input type="submit" name="submit" value="Log In"></td>
	</tr>
</table>
</form>
</div>

</body>
</html>