<!DOCTYPE  html>
<head>
	<title>Praetorian Request Form</title>
	<?php include_once("style.php") ?>
</head>
<body>

<?php include_once("navbar.php") ?>

<div class="form">
<form action="/request/add" target="_blank" method="post">
	<fieldset>
		<legend>General Information</legend>
		<table>
		
		<tr>
		<td><label for="name">Full Name:</label></td>
		<td><input type="text" name="name" maxlength="50"></td>
		</tr>
		
		<tr>
		<td><label for="email">Email:</label></td>
		<td><input type="email" name="email" maxlength="50"></td>
		</tr>

		</table>
	</fieldset>

	<fieldset>
		<legend>Request Details</legend>
		<table>

		<tr>
		<td><label for="category">Category:</label></td>

		<td><select name="category" size="1">
		<option>On-site Tech Support</option>
		<option>Remote Tech Support</option>
		<option>Penetration Testing</option>
		<option>Network Topography</option>
		</select></td>
		</tr>
		

		<tr>
		<td><label for="details">Additional Details:</label></td>

		<td><textarea name="description" rows="10" cols="30" maxlength="300"></textarea></td>

		</tr>

		<tr>
		<td><label for="date">Date of Booking:</label></td>
		<td><input type="date" name="date"></td>
		</tr>

		</table>
	</fieldset>
	
	<input type="submit" value="SUBMIT">	

</form>
</div>

</body>
</html>